//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace PBW2AutoPlrClient.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("beta.pbw.spaceempires.net/")]
        public string pbw_address {
            get {
                return ((string)(this["pbw_address"]));
            }
            set {
                this["pbw_address"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Xintus")]
        public string user_login {
            get {
                return ((string)(this["user_login"]));
            }
            set {
                this["user_login"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("xintusRules")]
        public string user_password {
            get {
                return ((string)(this["user_password"]));
            }
            set {
                this["user_password"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("login/process")]
        public string pbw_login_path {
            get {
                return ((string)(this["pbw_login_path"]));
            }
            set {
                this["pbw_login_path"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("node/player")]
        public string pbw_games_list_path {
            get {
                return ((string)(this["pbw_games_list_path"]));
            }
            set {
                this["pbw_games_list_path"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("player-turn/download")]
        public string pbw_player_download_path {
            get {
                return ((string)(this["pbw_player_download_path"]));
            }
            set {
                this["pbw_player_download_path"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("player-turn/upload")]
        public string pbw_upload_playerfile_path {
            get {
                return ((string)(this["pbw_upload_playerfile_path"]));
            }
            set {
                this["pbw_upload_playerfile_path"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("plr_file")]
        public string pbw_uploadFormParam_player {
            get {
                return ((string)(this["pbw_uploadFormParam_player"]));
            }
            set {
                this["pbw_uploadFormParam_player"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("downloadfiles\\")]
        public string user_download_path {
            get {
                return ((string)(this["user_download_path"]));
            }
            set {
                this["user_download_path"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool user_savelogin {
            get {
                return ((bool)(this["user_savelogin"]));
            }
            set {
                this["user_savelogin"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("games/")]
        public string pbw_game_path {
            get {
                return ((string)(this["pbw_game_path"]));
            }
            set {
                this["pbw_game_path"] = value;
            }
        }
    }
}
