//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBW2AutoPlrClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("beta.pbw.spaceempires.net/")]
        public string pbw_address {
            get {
                return ((string)(this["pbw_address"]));
            }
            set {
                this["pbw_address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xintus")]
        public string user_login {
            get {
                return ((string)(this["user_login"]));
            }
            set {
                this["user_login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xintusRules")]
        public string user_password {
            get {
                return ((string)(this["user_password"]));
            }
            set {
                this["user_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("login/process")]
        public string pbw_login_path {
            get {
                return ((string)(this["pbw_login_path"]));
            }
            set {
                this["pbw_login_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("node/player")]
        public string pbw_games_list_path {
            get {
                return ((string)(this["pbw_games_list_path"]));
            }
            set {
                this["pbw_games_list_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("player-turn/download")]
        public string pbw_player_download_path {
            get {
                return ((string)(this["pbw_player_download_path"]));
            }
            set {
                this["pbw_player_download_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("player-turn/upload")]
        public string pbw_upload_playerfile_path {
            get {
                return ((string)(this["pbw_upload_playerfile_path"]));
            }
            set {
                this["pbw_upload_playerfile_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("plr_file")]
        public string pbw_uploadFormParam_player {
            get {
                return ((string)(this["pbw_uploadFormParam_player"]));
            }
            set {
                this["pbw_uploadFormParam_player"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("downloadfiles\\")]
        public string user_download_path {
            get {
                return ((string)(this["user_download_path"]));
            }
            set {
                this["user_download_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool user_savelogin {
            get {
                return ((bool)(this["user_savelogin"]));
            }
            set {
                this["user_savelogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("games/")]
        public string pbw_game_path {
            get {
                return ((string)(this["pbw_game_path"]));
            }
            set {
                this["pbw_game_path"] = value;
            }
        }
    }
}
